In [1]:
pwd


'C:\\Users\\Lenovo\\Desktop\\AI\\Ml_Data'

In [2]:
a=100

In [3]:
a


100

In [5]:
print(type(a))

<class 'int'>


In [6]:
print(type(a))

<class 'int'>


In [7]:
a=[11,22,20,1,0,9]



In [8]:
a

[11, 22, 20, 1, 0, 9]

In [9]:
a[-1]


9

In [10]:
a[:5:1]

[11, 22, 20, 1, 0]

In [11]:
a[:2:1]

[11, 22]

In [12]:
a[3:2:1]

[]

In [13]:
a[::-1]

[9, 0, 1, 20, 22, 11]

In [14]:
a[2:19]

[20, 1, 0, 9]

In [15]:
import numpy as np


In [16]:
a=np.array([11,12,13,14,15,16,17])


In [17]:
type(a)

numpy.ndarray

In [18]:
len(a)

7

In [19]:
a.dtype
a.size
a.shape
a.ndim

1

In [20]:
a.dtype

dtype('int32')

In [21]:
a.size

7

In [22]:
a.shape

(7,)

In [23]:
a=np.array([[11,12,13],[14,15,16],[17,18,19]])


In [24]:
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [25]:
a.ndim

2

In [26]:
a[0,0]


11

In [27]:
a[0,]

array([11, 12, 13])

In [29]:
a[:0]

array([], shape=(0, 3), dtype=int32)

In [30]:
a[:,0]

array([11, 14, 17])

In [31]:
a[1:,:3]

array([[14, 15, 16],
       [17, 18, 19]])

In [32]:
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [33]:
a[:2,1:]

array([[12, 13],
       [15, 16]])

In [34]:
a[0::2,0::2]

array([[11, 13],
       [17, 19]])

In [35]:
a[::-1]

array([[17, 18, 19],
       [14, 15, 16],
       [11, 12, 13]])

In [36]:
a[::-1,::-1]

array([[19, 18, 17],
       [16, 15, 14],
       [13, 12, 11]])

In [37]:
import numpy as np


[sour:sweet] if sour cancels sweet than neutral

In [39]:
fruit_feature=np.array([[1,9],[2,8],[3,7],[2,8],[6,4],[9,1],[8,2],[9,1],[1,1],[5,5]])

In [40]:
fruit_feature

array([[1, 9],
       [2, 8],
       [3, 7],
       [2, 8],
       [6, 4],
       [9, 1],
       [8, 2],
       [9, 1],
       [1, 1],
       [5, 5]])

In [47]:
fruit_target=np.array(["sour","sour","sour","sour","sweet","sweet","sweet","sweet","none","none"])

In [48]:
fruit_target.shape

(10,)

In [49]:
from sklearn.neighbors import KNeighborsClassifier

In [50]:
trainer=KNeighborsClassifier()

In [51]:
learner=trainer.fit(fruit_feature,fruit_target)

In [46]:
learner.predict([[7,3]])

array(['sweet'], dtype='<U5')

In [ ]:
learner.predict([[7,9]])

In [ ]:
learner.predict([[4,4]])

In [ ]:
learner.predict([[1,1]])

In [ ]:
learner.predict([[0,0]])

In [ ]:
trainer=KNeighborsClassifier(n_neighbors=1)

In [ ]:
learner.predict([[2,2]])

In [ ]:
learner=trainer.fit(fruit_feature,fruit_target)


In [ ]:
learner.predict([[1,1]])